name: SSH Server Connection Check

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH connection
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 194.164.74.155
          username: u670292903
          password: ${{ secrets.SSH_PASSWORD }}
          port: 65002
          script: |
            echo "Connexion OK"
            php --version
            wp --info
